jenkins:
  systemMessage: "Jenkins Server"
  numExecutors: 5
  scmCheckoutRetryCount: 2
  mode: NORMAL

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

unclassified:
  location:
    adminAddress: "betoliveirame@icloud.com"
    url: "http://ci-server.local:8080/"

  simple-theme-plugin:
    elements:
    - cssUrl:
        url: "https://tobix.github.io/jenkins-neo2-theme/dist/neo-light.css"